name: ABodyBuilder2
description: Predict antibody structures from sequence and save them in PDB format
url: https://github.com/oxpig/ImmuneBuilder
authors:
  - Marc Horlacher
input:
  - CSV file with antibody VH, VL sequences
output:
  - Directory with PDB files